services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    expose: [ "5432" ]
    networks:
      - backend
    volumes: [ "pg:/var/lib/postgresql/data" ]

  qdrant:
    image: qdrant/qdrant:v1.12.5
    expose: [ "6333" ]
    networks:
      - backend
    volumes: [ "qdrant:/qdrant/storage" ]

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: [ "9001:9001" ]
    expose:
      - 9000
    networks:
      - backend
    volumes: [ "minio:/data" ]

  embeddings:
    build: ../../apps/embeddings-service
    expose:
      - "8082"
    networks:
      - backend
    environment:
      - MODEL_PATH=/models/sentence-transformer

  studio-api:
    image: mcr.microsoft.com/dotnet/sdk:10.0 # use sdk for dotnet watch, otherwise build image
    working_dir: /app
    volumes:
      - ../../apps/studio-api:/app
    command: [ "dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080" ]
    expose:
      - "8080"
    networks:
      - backend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: [ postgres, qdrant, minio ]

  recommender-api:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    working_dir: /app
    volumes:
      - ../../apps/recommender-api:/app
    command: [ "dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080" ]
    expose:
      - "8080"
    networks:
      - backend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: [ postgres, qdrant, minio ]

  gateway:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    working_dir: /app
    volumes:
      - ../../apps/gateway:/app
    command: [ "dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080" ]
    ports: [ "8080:8080" ]
    networks:
      - backend
    depends_on: [ studio-api, recommender-api, embeddings ]

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: start-dev --import-realm
    volumes:
      - ../keycloak/keycloak-realm.json:/opt/keycloak/data/import/realm-elsewhere.json
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8085:8080"
    networks:
      - backend

volumes: { pg: {}, qdrant: {}, minio: {} }
networks:
  backend: