services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    expose: [ "5432" ]
    networks:
      - backend
    volumes: [ "pg:/var/lib/postgresql/data" ]

  qdrant:
    image: qdrant/qdrant:v1.12.5
    expose: [ "6333" ]
    networks:
      - backend
    volumes: [ "qdrant:/qdrant/storage" ]

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: [ "9001:9001" ]
    expose:
      - 9000
    networks:
      - backend
    volumes: [ "minio:/data" ]

  embeddings:
    build: ../../apps/embeddings-service
    expose:
      - "8082"
    networks:
      - backend
    environment:
      - MODEL_PATH=/models/sentence-transformer

  studio-api:
    build: 
      context: ../../
      dockerfile: apps/studio-api/Dockerfile
    networks:
      - backend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: [ postgres, qdrant, minio, aspire-dashboard ]

  recommender-api:
    build:
      context: ../../
      dockerfile: apps/recommender-api/Dockerfile
    networks:
      - backend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: [ postgres, qdrant, minio, aspire-dashboard ]

  gateway:
    build: 
      context: ../../
      dockerfile: apps/gateway/Dockerfile
    ports: [ "8080:8080" ]
    networks:
      - backend
    depends_on: [ studio-api, recommender-api, embeddings, aspire-dashboard ]

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: start-dev --import-realm
    volumes:
      - ../keycloak/keycloak-realm.json:/opt/keycloak/data/import/realm-elsewhere.json
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8085:8080"
    networks:
      - backend

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: aspire-dashboard
    ports:
      - "18888:18888" # web UI
      - "18889:18889" # OTLP gRPC
    networks:
      - backend


volumes: { pg: {}, qdrant: {}, minio: {} }
networks:
  backend: